server:
  port: 8081
  servlet:
    context-path: /community
mybatis:
  mapper-locations: classpath:/mapper/*.xml
    # 存放实体类的包名
  type-aliases-package: com.newcoder.community.entity
  configuration:
    # id自增长
    use-generated-keys: true
    # 让下划线命名 和 驼峰命名匹配
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: true
      maximum-pool-size: 15
      minimum-idle: 5
      max-lifetime: 30000
    type: com.zaxxer.hikari.HikariDataSource
  thymeleaf:
    cache: false
  mail:
    host: smtp.sina.com
    username: liyihong1997@sina.com
    # 填的授权码，这里不是密码
    password: da03a4b2fd0d1133
    protocol: smtps
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable:
              true
  application:
    name: community
app:
  domain: http://127.0.0.1:8081
#debug: true
  upload-path: G:/data/images