server:
  port: 8081
  servlet:
    context-path: /community
mybatis:
  mapper-locations: classpath:/mapper/*.xml
    # 存放实体类的包名
  type-aliases-package: com.newcoder.community.entity
  configuration:
    # id自增长
    use-generated-keys: true
    # 让下划线命名 和 驼峰命名匹配
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 15
      minimum-idle: 5
      max-lifetime: 30000
    type: com.zaxxer.hikari.HikariDataSource

